export const UPDATE_MOVIES_LIST = '@movies/UPDATE_MOVIES_LIST';
export const UPDATE_MOVIES_LOADING = '@movies/UPDATE_MOVIES_LOADING';
export const UPDATE_MOVIES_ITEM = '@movies/UPDATE_MOVIES_ITEM';
export const UPDATE_MOVIES_ADD = '@movies/UPDATE_MOVIES_ADD';
